DELETE FROM `smart_scripts` WHERE `entryorguid`=19401 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (19401, 0, 0, 0, 62, 0, 100, 0, 7967, 0, 0, 0, 11, 33825, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Wing Commamder Brack - On gossip option 0 select - Cast Aerial Assault Flight (Horde)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (19401, 0, 1, 0, 62, 0, 100, 0, 7967, 1, 0, 0, 11, 33825, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Wing Commamder Brack - On gossip option 1 select - Cast Aerial Assault Flight (Horde)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (19401, 0, 2, 0, 62, 0, 100, 0, 7967, 4, 0, 0, 11, 34578, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Wing Commamder Brack - On gossip option 4 select - Cast Taxi - Reaver\'s Fall to Spinebreaker Ridge');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (19401, 0, 3, 0, 62, 0, 100, 0, 7967, 5, 0, 0, 11, 33659, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Wing Commamder Brack - On gossip option 5 select - Cast Gateways Murket and Shaadraz');

UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=19401;


DELETE FROM `gossip_menu_option` WHERE `menu_id`=7967 AND `id`=0;
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (7967, 0, 0, 'Send me to the Abyssal Shelf!', 1, 1, 0, 0, 0, 0, '');
DELETE FROM `gossip_menu_option` WHERE `menu_id`=7967 AND `id`=1;
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (7967, 1, 0, 'Send me to the Abyssal Shelf!', 1, 1, 0, 0, 0, 0, '');
DELETE FROM `gossip_menu_option` WHERE `menu_id`=7967 AND `id`=4;
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (7967, 4, 0, 'Lend me a Windrider.  I\'m going to Spinebreaker Post!', 1, 1, 0, 0, 0, 0, '');
DELETE FROM `gossip_menu_option` WHERE `menu_id`=7967 AND `id`=5;
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`) VALUES (7967, 5, 0, 'I\'m on a bombing mission for Forward Commander To\'arch.  I need a wyvern destroyer!', 1, 1, 0, 0, 0, 0, '');


