DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=69099 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (69099, 0, 32518, 'Nalak, the Storm Lord');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=87437 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (87437, 0, 37460, 'Drov the Ruiner');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=81535 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (81535, 0, 37462, 'Tarlna the Ageless');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=87493 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (87493, 0, 37474, 'Rhukmar');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=94015 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (94015, 0, 39380, 'Supreme Lord Kazzak');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=95068 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (95068, 0, 39473, 'Siegemaster Mar\'tak');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=90284 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (90284, 0, 39474, 'Iron Reaver');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=90776 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (90776, 0, 39475, 'Komrok');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=90378 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (90378, 0, 39476, 'Kilrogg Deadeye');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=92146 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (92146, 0, 39477, 'Gurtogg Bloodboil (Council)');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=91809 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (91809, 0, 39478, 'Gorefiend');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=90316 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (90316, 0, 39479, 'Shadow-Lord Iskar');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=90296 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (90296, 0, 39480, 'Socrethar the Eternal');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=89890 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (89890, 0, 39481, 'Fel Lord Zakuun');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=93068 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (93068, 0, 39482, 'Xhul\'horac');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=93439 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (93439, 0, 39483, 'Tyrant Velhari');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=91349 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (91349, 0, 39484, 'Mannoroth');
DELETE FROM `boss_loot_weekly_quest` WHERE `entry`=91331 AND `difficulty`=0;
INSERT INTO `boss_loot_weekly_quest` (`entry`, `difficulty`, `questId`, `comment`) VALUES (91331, 0, 39485, 'Archimonde');
