UPDATE `quest_template` SET `OfferRewardEmote1`=6 WHERE `Id`=28490; -- Quest "Hero's Call: Darkshore!"
UPDATE `quest_template` SET `DetailsEmote1`=1, `OfferRewardEmote1`=2 WHERE `Id`=13518; -- Quest "The Last Wave of Survivors"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=6, `OfferRewardEmote1`=1, `RequestItemsText`="Have you cleared the coast?" WHERE `Id`=13522; -- Quest "Threat from the Water"
UPDATE `quest_template` SET `DetailsEmote1`=2, `DetailsEmote2`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1 WHERE `Id`=13520; -- Quest "The Boon of the Seas"
UPDATE `quest_template` SET `DetailsEmote1`=5 WHERE `Id`=13521; -- Quest "Buzzbox 413"
UPDATE `quest_template` SET `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=1 WHERE `Id`=13527; -- Quest "No Accounting for Taste"
UPDATE `quest_template` SET `DetailsEmote1`=1 WHERE `Id`=13528; -- Quest "Buzzbox 723"
UPDATE `quest_template` SET `EmoteOnIncomplete`=3, `EmoteOnComplete`=3, `OfferRewardEmote1`=5 WHERE `Id`=13554; -- Quest "A Cure In The Dark"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `OfferRewardEmote1`=1, `RequestItemsText`="This is never desirable work. Zenn was not always the corrupt being that you now see. Sadly, he is behind reproach at this point. Much of the damage that he has done to nature is irreversible." WHERE `Id`=13529; -- Quest "The Corruption's Source"
UPDATE `quest_template` SET `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=1 WHERE `Id`=13557; -- Quest "Bearer of Good Fortune"
UPDATE `quest_template` SET `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=273, `OfferRewardEmote2`=1 WHERE `Id`=13831; -- Quest "A Troubling Prescription"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1 WHERE `Id`=13537; -- Quest "A Taste for Grouper"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=2 WHERE `Id`=13563; -- Quest "A Love Eternal"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `OfferRewardEmote1`=1, `RequestItemsText`="The flames of Bashal'Aran were beacons of hope for our fallen ancestors. We cannot abandon hope entirely, but it is time that we come to terms with the fate that we've earned. They will find peace in a final death, and in time, we will join them again." WHERE `Id`=13562; -- Quest "The Final Flame of Bashal'Aran"
UPDATE `quest_template` SET `DetailsEmote1`=1, `OfferRewardEmote1`=1, `RequestItemsText`="Is it done?" WHERE `Id`=13561; -- Quest "Solace for the Highborne"
UPDATE `quest_template` SET `RequestItemsText`="We have learned the lessons of discretion in the past. I hope that you can find it within you to trust me when I tell you that there is no hope of establishing any continued relations with the naga." WHERE `Id`=13565; -- Quest "Twice Removed"
UPDATE `quest_template` SET `RequestItemsText`="The great spirits have been here longer than I can remember. They were once mortal animals if all the stories are true, and they died in time of dire fates." WHERE `Id`=13569; -- Quest "The Ritual Bond"
UPDATE `quest_template` SET `OfferRewardEmote1`=1 WHERE `Id`=13599; -- Quest "Grimclaw's Return"
UPDATE `quest_template` SET `DetailsEmote1`=1, `OfferRewardEmote1`=6 WHERE `Id`=13589; -- Quest "The Shatterspear Invaders"
UPDATE `quest_template` SET `DetailsEmote1`=1, `OfferRewardEmote1`=5 WHERE `Id`=13560; -- Quest "An Ocean Not So Deep"
UPDATE `quest_template` SET `DetailsEmote1`=1, `OfferRewardEmote1`=1 WHERE `Id`=13504; -- Quest "Shatterspear Laborers"
UPDATE `quest_template` SET `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=1 WHERE `Id`=13505; -- Quest "Remnants of the Highborne"
UPDATE `quest_template` SET `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=1 WHERE `Id`=13506; -- Quest "Reason to Worry"
UPDATE `quest_template` SET `DetailsEmote1`=1 WHERE `Id`=13508; -- Quest "Swift Response"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=3, `OfferRewardEmote1`=1, `RequestItemsText`="Hello again, $n." WHERE `Id`=13509; -- Quest "War Supplies"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=6, `OfferRewardEmote1`=1, `RequestItemsText`="Have you finished the deed?" WHERE `Id`=13507; -- Quest "Denying Manpower"
UPDATE `quest_template` SET `OfferRewardEmote1`=1 WHERE `Id`=13511; -- Quest "One Bitter Wish"
UPDATE `quest_template` SET `DetailsEmote1`=1, `OfferRewardEmote1`=6 WHERE `Id`=13510; -- Quest "Timely Arrival"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `OfferRewardEmote1`=1, `RequestItemsText`="It's good to see you back." WHERE `Id`=13512; -- Quest "Strategic Strikes"
UPDATE `quest_template` SET `DetailsEmote1`=3, `DetailsEmote2`=1, `DetailsEmote3`=273, `OfferRewardEmote1`=273, `OfferRewardEmote2`=1 WHERE `Id`=13844; -- Quest "The Looting of Althalaxx"
UPDATE `quest_template` SET `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=1 WHERE `Id`=13513; -- Quest "On the Brink"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnComplete`=6, `OfferRewardEmote1`=1 WHERE `Id`=13590; -- Quest "The Front Line"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `OfferRewardEmote1`=1, `RequestItemsText`="I have no yearning for war, but I've had sufficient reason to worry that we'd get rusty after so much time away from the front lines. It's good to see that the Sentinels and the ancients are every bit as dangerous as I remember them." WHERE `Id`=13514; -- Quest "The Ancients' Ire"
UPDATE `quest_template` SET `DetailsEmote1`=1, `OfferRewardEmote1`=1, `RequestItemsText`="As it should be." WHERE `Id`=13515; -- Quest "Ending the Threat"
UPDATE `quest_template` SET `OfferRewardEmote1`=1 WHERE `Id`=13591; -- Quest "Disturbing Connections"
UPDATE `quest_template` SET `OfferRewardEmote1`=1, `OfferRewardEmote2`=1, `OfferRewardEmote3`=1, `OfferRewardEmote4`=2 WHERE `Id`=13570; -- Quest "Remembrance of Auberdine"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=6, `OfferRewardEmote1`=1, `RequestItemsText`="Do you think you could go back to the Ruins of Auberdine and destroy more bracers?" WHERE `Id`=13542; -- Quest "Against the Wind"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `EmoteOnIncomplete`=1, `OfferRewardEmote1`=6, `RequestItemsText`="I sense that you have not quite coaxed each of the spirits of the four I sent you after. Return when you have, and $n, hurry. We are almost out of time!" WHERE `Id`=13547; -- Quest "Coaxing the Spirits"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `DetailsEmote3`=25, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=6, `OfferRewardEmote2`=2, `OfferRewardEmoteDelay2`=2000 WHERE `Id`=13558; -- Quest "Call Down the Thunder"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=25, `EmoteOnIncomplete`=6, `OfferRewardEmote1`=2, `RequestItemsText`="The three Twilight's Hammer cultists have still not been dealt with. Is there a problem, $n?" WHERE `Id`=13543; -- Quest "Three Hammers to Break"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=5, `DetailsEmote3`=25, `OfferRewardEmote1`=2 WHERE `Id`=13605; -- Quest "The Last Refugee"
UPDATE `quest_template` SET `RequestItemsText`="The land is deeply unsettled, $n. It'll be years before calm returns to these parts." WHERE `Id`=13584; -- Quest "Calming the Earth"
UPDATE `quest_template` SET `RequestItemsText`="Is it done yet, $n?" WHERE `Id`=13576; -- Quest "Mutual Aid"
UPDATE `quest_template` SET `RequestItemsText`="Is it done, $n?" WHERE `Id`=13580; -- Quest "Soothing the Elements"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `OfferRewardEmote1`=1, `OfferRewardEmote2`=1 WHERE `Id`=13525; -- Quest "What's Happening to the Blackwood Furbolg?"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1 WHERE `Id`=13526; -- Quest "The Bear's Paw"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1 WHERE `Id`=13544; -- Quest "The Bear's Blessing"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `OfferRewardEmote1`=1, `OfferRewardEmote2`=1, `RequestItemsText`="Have your efforts and the bear's blessing cleansed my brothers?" WHERE `Id`=13545; -- Quest "Cleansing the Afflicted"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `OfferRewardEmote1`=1, `OfferRewardEmote2`=1, `RequestItemsText`="Have you destroyed the Jadefire braziers?" WHERE `Id`=13572; -- Quest "Jadefire Braziers"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `OfferRewardEmote1`=1, `OfferRewardEmote2`=1, `RequestItemsText`="Have you defeated the satyr who poisons our land?" WHERE `Id`=13546; -- Quest "The Defiler"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=274, `EmoteOnIncomplete`=1, `OfferRewardEmote1`=1, `OfferRewardEmote2`=1, `RequestItemsText`="It's a shame that those animals were beyond saving. If only I'd discovered the problem sooner!$B$BWere you able to find the source?" WHERE `Id`=13881; -- Quest "Consumed"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=4, `OfferRewardEmote2`=1 WHERE `Id`=13882; -- Quest "The Seeds of Life"
UPDATE `quest_template` SET `RequestItemsText`="Have you completed your scouting mission, $n?" WHERE `Id` in (13892,13948); -- Quests "Leave No Tracks" & "Stepping Up Surveillance"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=6, `OfferRewardEmote1`=21, `OfferRewardEmote2`=1 WHERE `Id`=13925; -- Quest "An Ounce of Prevention"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=25, `OfferRewardEmote1`=6, `RequestItemsText`="Nothing makes me feel more alive than soaring through the trees! Did we protect enough animals? Do we need to take another pass?" WHERE `Id`=13885; -- Quest "In Defense of Darkshore"
UPDATE `quest_template` SET `DetailsEmote1`=274, `DetailsEmote2`=5, `OfferRewardEmote1`=4, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6 WHERE `Id`=13891; -- Quest "The Devourer of Darkshore"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=5, `OfferRewardEmote1`=1, `OfferRewardEmote2`=15, `EmoteOnIncomplete`=6, `RequestItemsText`="I hear a lot of gurgling down there. What's going on?" WHERE `Id`=13907; -- Quest "Sweeping Clean the Ruins"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=273, `DetailsEmote3`=6, `OfferRewardEmote1`=21, `OfferRewardEmote2`=1, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6 WHERE `Id`=13912; -- Quest "Swamped Secrets"
UPDATE `quest_template` SET `OfferRewardEmote1`=1, `OfferRewardEmote2`=5 WHERE `Id`=13911; -- Quest "The Absent-Minded Prospector"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=25, `DetailsEmote3`=273, `OfferRewardEmote1`=4, `OfferRewardEmote2`=5, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardText`="Why yes, yes, this is it! See here, the slot is the exact dimensions of the ancient disc, just as I'd surmised. Here's your reward, $n - you've earned it.$B$B<Jr. Archaeologist Ferd upends the device and pours mud and garbage from the slot.>$B$BAre you ready to meet history face to face? Let's see what the ancients have to say!" WHERE `Id`=13918; -- Quest "The Titans' Terminal"
UPDATE `quest_template` SET `DetailsEmote1`=6, `DetailsEmote2`=1, `OfferRewardEmote1`=11, `OfferRewardEmote2`=1 WHERE `Id`=13909; -- Quest "Got Some Flotsam?"
UPDATE `quest_template` SET `DetailsEmote1`=25, `DetailsEmote2`=274, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=6, `OfferRewardEmote2`=274 WHERE `Id`=13910; -- Quest "A New Home"
UPDATE `quest_template` SET `RequestItemsText`="You return, $n. What news do you bring?" WHERE `Id`=13898; -- Quest "The Tides Turn Against Us"
UPDATE `quest_template` SET `DetailsEmote1`=1, `OfferRewardEmote1`=1 WHERE `Id`=26408; -- Quest "Ashes in Ashenvale"
UPDATE `quest_template` SET `OfferRewardEmote1`=2 WHERE `Id`=5713; -- Quest "One Shot. One Kill."
UPDATE `quest_template` SET `EmoteOnComplete`=6, `OfferRewardEmote1`=6 WHERE `Id`=28529; -- Quest "Writings of the Void"