UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1 WHERE `Id`=1581; -- Quest "Elixirs for the Bladeleafs"
UPDATE `quest_template` SET `RequestItemsText`="I adore these forests. I want to see the corruption purged from them completely. When next I return, I want to do so with a lighter heart.", `QuestGiverTextWindow`="With Githyiss lie clues to the corruption of Shadowglen and the rest of Teldrassil.", `QuestGiverTargetName`="Githyiss the Vile", `QuestGiverPortrait`=759 WHERE `Id`=28727; -- Quest "Vile Touch"
UPDATE `quest_template` SET `OfferRewardEmote1`=1 WHERE `Id`=938; -- Quest "Mist"
UPDATE `quest_template` SET `DetailsEmote1`=2, `DetailsEmote2`=1, `EmoteOnIncomplete`=1, `OfferRewardEmote1`=21 WHERE `Id`=28713; -- Quest "The Balance of Nature"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1 WHERE `Id`=28714; -- Quest "Fel Moss Corruption"
UPDATE `quest_template` SET `DetailsEmote1`=1, `OfferRewardEmote1`=6, `OfferRewardText`="Ilthalaine sent you? He was wise to do so. I am indeed in need of help." WHERE `Id`=28734; -- Quest "A Favor for Melithar"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=5 WHERE `Id`=28715; -- Quest "Demonic Thieves"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnComplete`=2, `OfferRewardEmote1`=1, `OfferRewardEmote2`=1 WHERE `Id`=31168; -- Quest "Calligraphed Sigil"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1, `OfferRewardEmote2`=1 WHERE `Id`=3116; -- Quest "Simple Sigil"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `OfferRewardEmote1`=1, `OfferRewardText`="You've proven a capable student. When it is time to resume your training, return to me and I will show you other techniques." WHERE `Id`=26945; -- Quest "Learning New Techniques"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1, `OfferRewardEmote2`=1 WHERE `Id`=3117; -- Quest "Etched Sigil"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `OfferRewardEmote1`=1 WHERE `Id`=26947; -- Quest "A Woodsman's Training"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnComplete`=2, `OfferRewardEmote1`=1, `OfferRewardEmote2`=1 WHERE `Id`=3118; -- Quest "Encrypted Sigil"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `OfferRewardEmote1`=1 WHERE `Id`=26946; -- Quest "A Rogue's Advantage"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnComplete`=2, `OfferRewardEmote1`=1, `OfferRewardEmote2`=1 WHERE `Id`=3119; -- Quest "Hallowed Sigil"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `OfferRewardEmote1`=1 WHERE `Id`=26949; -- Quest "Learning the Word"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1, `OfferRewardEmote2`=1 WHERE `Id`=3120; -- Quest "Verdant Sigil"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `OfferRewardEmote1`=1 WHERE `Id`=26948; -- Quest "Moonfire"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=2, `OfferRewardEmote2`=1 WHERE `Id`=26841; -- Quest "Forbidden Sigil"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `OfferRewardEmote1`=1 WHERE `Id`=26940; -- Quest "Frost Nova"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `OfferRewardEmote1`=1 WHERE `Id`=31169; -- Quest "The Art of the Monk"
UPDATE `quest_template` SET `DetailsEmote1`=1, `OfferRewardEmote1`=1 WHERE `Id`=28723; -- Quest "Priestess of the Moon"
UPDATE `quest_template` SET `DetailsEmote1`=1, `OfferRewardEmote1`=2 WHERE `Id`=28724; -- Quest "Iverron's Antidote"
UPDATE `quest_template` SET `DetailsEmote1`=1 WHERE `Id`=28725; -- Quest "The Woodland Protector"
UPDATE `quest_template` SET `OfferRewardEmote1`=1 WHERE `Id`=28728; -- Quest "Signs of Things to Come"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1 WHERE `Id`=28729; -- Quest "Teldrassil: Crown of Azeroth"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1 WHERE `Id`=28730; -- Quest "Precious Waters"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1 WHERE `Id`=28731; -- Quest "Teldrassil: Passing Awareness"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=1 WHERE `Id`=2159; -- Quest "Dolanaar Delivery"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1 WHERE `Id`=929; -- Quest "Teldrassil: The Refusal of the Aspects"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1 WHERE `Id`=6344; -- Quest "Reminders of Home"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1 WHERE `Id`=6341; -- Quest "To Darnassus"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=1 WHERE `Id`=6342; -- Quest "An Unexpected Gift"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=1 WHERE `Id`=6343; -- Quest "Return to Nyoma"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=5 WHERE `Id`=489; -- Quest "Seek Redemption!"
UPDATE `quest_template` SET `EmoteOnIncomplete`=6, `OfferRewardEmote1`=1 WHERE `Id`=13946; -- Quest "Nature's Reprisal"
UPDATE `quest_template` SET `DetailsEmote1`=2, `DetailsEmoteDelay1`=500, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=2, `QuestGiverTextWindow`="None speak of the traitorous tale of Melenas, but his presence serves as a bitter, embarrassing reminder that trust must be earned, not given freely.", `QuestGiverTargetName`="Lord Melenas", `QuestGiverPortrait`=1013 WHERE `Id`=932; -- Quest "Twisted Hatred"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `DetailsEmote3`=25 WHERE `Id`=475; -- Quest "A Troubling Breeze"
UPDATE `quest_template` SET `OfferRewardEmote1`=5 WHERE `Id`=476; -- Quest "Gnarlpine Corruption"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=4 WHERE `Id`=2438; -- Quest "The Emerald Dreamcatcher"
UPDATE `quest_template` SET `DetailsEmote1`=15, `DetailsEmote2`=1, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=2, `QuestGiverTextWindow`="The corruption of the gnarlpine draws a grim shroud over the fate of all of the sleeping night elf druids. Without protection, their fragile bodies will not last.", `QuestGiverTargetName`="Ferocitas the Dream Eater", `QuestGiverPortrait`=1996 WHERE `Id`=2459; -- Quest "Ferocitas the Dream Eater"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=21 WHERE `Id`=483; -- Quest "The Relics of Wakening"
UPDATE `quest_template` SET `DetailsEmote1`=2, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=2 WHERE `Id`=2541; -- Quest "The Sleeping Druid"
UPDATE `quest_template` SET `DetailsEmote1`=2, `EmoteOnIncomplete`=1, `OfferRewardEmote1`=1, `QuestGiverTextWindow`="With spirit and body torn apart, only one option remains to free this sleeping druid from eternal torment.", `QuestGiverTargetName`="Rageclaw", `QuestGiverPortrait`=6230 WHERE `Id`=2561; -- Quest "Druid of the Claw"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `OfferRewardEmote1`=1, `OfferRewardEmote2`=2, `QuestGiverTextWindow`="Dreaded leader of the Gnarlpine Furbolg, Ursal seems to defy death itself in his pursuit of further corrupting Teldrassil. If the wilds are to be healed, Ursal must die.", `QuestGiverTargetName`="Ursal the Mauler", `QuestGiverPortrait`=6818 WHERE `Id`=486; -- Quest "Ursal the Mauler"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=1, `EmoteOnIncomplete`=274, `OfferRewardEmote1`=66 WHERE `Id`=487; -- Quest "The Road to Darnassus"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=6, `OfferRewardEmote1`=1, `RequestItemsText`="Are their numbers weakened?" WHERE `Id`=13945; -- Quest "Resident Danger"
UPDATE `quest_template` SET `DetailsEmote1`=6, `DetailsEmote2`=1, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=1 WHERE `Id`=997; -- Quest "Denalan's Earth"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=2 WHERE `Id`=918; -- Quest "Timberling Seeds"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=1, `OfferRewardEmote2`=2 WHERE `Id`=919; -- Quest "Timberling Sprouts"
UPDATE `quest_template` SET `DetailsEmote1`=1, `DetailsEmote2`=2, `EmoteOnIncomplete`=2, `EmoteOnComplete`=2, `OfferRewardEmote1`=1 WHERE `Id`=922; -- Quest "Rellian Greenspyre"
UPDATE `quest_template` SET `OfferRewardEmote1`=5, `OfferRewardEmote2`=1 WHERE `Id`=930; -- Quest "The Glowing Fruit"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1 WHERE `Id`=7383; -- Quest "Teldrassil: The Burden of the Kaldorei"
UPDATE `quest_template` SET `DetailsEmote1`=1 WHERE `Id`=933; -- Quest "Teldrassil: The Coming Dawn"
UPDATE `quest_template` SET `RequestItemsText`="Did you find the source of the corruption?", `QuestGiverTextWindow`="As Malfurion tore the remains of Xavius from Teldrassil, a great weight was lifted from the dying world tree. One last remnant of Xavius remains to torment the night elf people, but Elune's champion approaches to finally free the tree completely.", `QuestGiverTargetName`="Bough of Corruption", `QuestGiverPortrait`=14383 WHERE `Id`=14005; -- Quest "The Vengeance of Elune"
UPDATE `quest_template` SET `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1 WHERE `Id`=935; -- Quest "The Waters of Teldrassil"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=1 WHERE `Id`=14039; -- Quest "Home of the Kaldorei"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=3, `EmoteOnComplete`=3, `OfferRewardEmote1`=2 WHERE `Id`=923; -- Quest "Mossy Tumors"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=1, `QuestGiverTextWindow`="Oakenscowl lingers as a dire reminder of how deep Teldrassil's corruption can spread, turning a being of pure nature into something of nightmare.", `QuestGiverTargetName`="Oakenscowl", `QuestGiverPortrait`=2567 WHERE `Id`=2499; -- Quest "Oakenscowl"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=1, `EmoteOnComplete`=1, `OfferRewardEmote1`=1 WHERE `Id`=937; -- Quest "The Enchanted Glade"
UPDATE `quest_template` SET `DetailsEmote1`=1, `EmoteOnIncomplete`=18, `EmoteOnComplete`=18, `OfferRewardEmote1`=2, `QuestGiverTextWindow`="Corruption and madness can consume even the purest of Elune's creatures. It falls to us to bring peace to those that deserve it most.", `QuestGiverTargetName`="Lady Sathrah", `QuestGiverPortrait`=6214 WHERE `Id`=2518; -- Quest "Tears of the Moon"
UPDATE `quest_template` SET `DetailsEmote1`=5, `DetailsEmote2`=1, `OfferRewardEmote1`=6 WHERE `Id`=26383; -- Quest "Breaking Waves of Change"
UPDATE `quest_template` SET `EmoteOnIncomplete`=0, `EmoteOnComplete`=0, `OfferRewardEmote1`=6, `OfferRewardEmote2`=2 WHERE `Id`=931; -- Quest "The Shimmering Frond"
UPDATE `quest_template` SET `EmoteOnIncomplete`=6, `EmoteOnComplete`=6, `OfferRewardEmote1`=5, `OfferRewardEmote2`=2 WHERE `Id`=927; -- Quest "The Moss-twined Heart"
UPDATE `quest_template` SET `DetailsEmote1`=1 WHERE `Id`=941; -- Quest "Planting the Heart"