DELETE FROM `access_requirement` WHERE `mapId`=1001 AND `difficulty`=2;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `itemlevel_min`, `itemlevel_max`, `quest_failed_text`, `comment`) VALUES (1001, 2, 90, 0, 0, 0, 0, 0, 0, 0, 0, '', 'Scarlet Monastery Halls');
DELETE FROM `access_requirement` WHERE `mapId`=1001 AND `difficulty`=1;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `itemlevel_min`, `itemlevel_max`, `quest_failed_text`, `comment`) VALUES (1001, 1, 21, 0, 0, 0, 0, 0, 0, 0, 0, '', 'Scarlet Monastery Halls');
DELETE FROM `access_requirement` WHERE `mapId`=1004 AND `difficulty`=1;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `itemlevel_min`, `itemlevel_max`, `quest_failed_text`, `comment`) VALUES (1004, 1, 23, 0, 0, 0, 0, 0, 0, 0, 0, '', 'Scarlet Monastery Cathedral');
DELETE FROM `access_requirement` WHERE `mapId`=1004 AND `difficulty`=2;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `itemlevel_min`, `itemlevel_max`, `quest_failed_text`, `comment`) VALUES (1004, 2, 90, 0, 0, 0, 0, 0, 0, 0, 0, '', 'Scarlet Monastery Cathedral');
DELETE FROM `access_requirement` WHERE `mapId`=1007 AND `difficulty`=1;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `itemlevel_min`, `itemlevel_max`, `quest_failed_text`, `comment`) VALUES (1007, 1, 33, 0, 0, 0, 0, 0, 0, 0, 0, '', 'Scholomance Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1007 AND `difficulty`=2;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `itemlevel_min`, `itemlevel_max`, `quest_failed_text`, `comment`) VALUES (1007, 2, 90, 0, 0, 0, 0, 0, 0, 0, 0, '', 'Scholomance Entrance');
