-- A Fowl Shortage SmartAI Support                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
UPDATE `creature_template` SET `npcflag`=1, `AIName`='SmartAI' WHERE `entry`=53568 LIMIT 1;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
-- Script
DELETE FROM `smart_scripts`  WHERE `entryorguid`=53568;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (53568, 0, 0, 1, 64, 0, 100, 0, 0, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Dun Morogh Chicken On Gossip Hello - Gossip Close');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (53568, 0, 1, 2, 61, 0, 100, 0, 0, 0, 0, 0, 56, 69982, 1, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Dun Morogh Chicken On Gossip Hello - Add item');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (53568, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 41, 1, 1, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Dun Morogh Chicken On Gossip Hello - Despawn');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
-- Condition
DELETE FROM `conditions` WHERE `SourceGroup`=1 AND `SourceEntry`=53568;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES (22, 1, 53568, 0, 0, 9, 0, 29352, 0, 0, 0, 0, '', 'A Fowl Shortage - Quest Condition');                                                                                                                                                                                         
                        