DELETE FROM `quest_template` WHERE `Id`=37455;
INSERT INTO `quest_template` (`Id`, `Title`) VALUES (37455, 'Sealing Fate: Immense Fortune of Gold');
DELETE FROM `quest_template` WHERE `Id`=37453;
INSERT INTO `quest_template` (`Id`, `Title`) VALUES (37453, 'Sealing Fate: Mountain of Apexis Crystals');
DELETE FROM `quest_template` WHERE `Id`=37457;
INSERT INTO `quest_template` (`Id`, `Title`) VALUES (37457, 'Sealing Fate: Tremendous Garrison Resources');
DELETE FROM `quest_template` WHERE `Id`=37459;
INSERT INTO `quest_template` (`Id`, `Title`) VALUES (37459, 'Sealing Fate: Monumental Honor');
DELETE FROM `quest_template` WHERE `Id`=36055;
INSERT INTO `quest_template` (`Id`, `Title`) VALUES (36055, 'Sealing Fate: Apexis Crystals');
DELETE FROM `quest_template` WHERE `Id`=37452;
INSERT INTO `quest_template` (`Id`, `Title`) VALUES (37452, 'Sealing Fate: Heap of Apexis Crystals');
DELETE FROM `quest_template` WHERE `Id`=36054;
INSERT INTO `quest_template` (`Id`, `Title`) VALUES (36054, 'Sealing Fate: Gold');
DELETE FROM `quest_template` WHERE `Id`=37454;
INSERT INTO `quest_template` (`Id`, `Title`) VALUES (37454, 'Sealing Fate: Piles of Gold');
DELETE FROM `quest_template` WHERE `Id`=36056;
INSERT INTO `quest_template` (`Id`, `Title`) VALUES (36056, 'Sealing Fate: Garrison Resources');
DELETE FROM `quest_template` WHERE `Id`=37456;
INSERT INTO `quest_template` (`Id`, `Title`) VALUES (37456, 'Sealing Fate: Stockpiled Garrison Resources');
DELETE FROM `quest_template` WHERE `Id`=36057;
INSERT INTO `quest_template` (`Id`, `Title`) VALUES (36057, 'Sealing Fate: Honor');
DELETE FROM `quest_template` WHERE `Id`=37458;
INSERT INTO `quest_template` (`Id`, `Title`) VALUES (37458, 'Sealing Fate: Extended Honor');
