DELETE FROM `creature_text` WHERE `entry`=864721 AND `groupid`=0 AND `id`=0;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (864721, 0, 0, 'I spoke with Warlord Volrath today. He is concerned that our troops are refusing to march into the burial grounds.', 12, 0, 100, 1, 0, 0, '');
DELETE FROM `creature_text` WHERE `entry`=864721 AND `groupid`=1 AND `id`=0;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (864721, 1, 0, 'The grunts that return from there are reporting sightings of strange spirits. They say that necromancers are enslaving the ghosts of the ancient ogres.', 12, 0, 100, 1, 0, 0, '');
DELETE FROM `creature_text` WHERE `entry`=864721 AND `groupid`=2 AND `id`=0;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (864721, 2, 0, 'You hear what happened? The blood elves say they found something big in the mines.', 12, 0, 100, 1, 0, 0, '');
DELETE FROM `creature_text` WHERE `entry`=864721 AND `groupid`=3 AND `id`=0;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (864721, 3, 0, 'Not an axe, dimwit! They say it\'s part of the big artifact the Alliance is looking for.', 12, 0, 100, 1, 0, 0, '');
DELETE FROM `creature_text` WHERE `entry`=864721 AND `groupid`=4 AND `id`=0;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (864721, 4, 0, 'Do you even understand why we\'re here in Ashran?', 12, 0, 100, 1, 0, 0, '');
DELETE FROM `creature_text` WHERE `entry`=864601 AND `groupid`=0 AND `id`=0;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (864601, 0, 0, 'Oh yeah? Why do you think that is?', 12, 0, 100, 6, 0, 0, '');
DELETE FROM `creature_text` WHERE `entry`=864601 AND `groupid`=1 AND `id`=0;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (864601, 1, 0, 'Ghost ogres? I can see why they\'d stay away. Not that I\'m afraid or anything, but I prefer enemies I can actually strike with an axe.', 12, 0, 100, 1, 0, 0, '');
DELETE FROM `creature_text` WHERE `entry`=864601 AND `groupid`=2 AND `id`=0;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (864601, 2, 0, 'What, like a really big axe?', 12, 0, 100, 6, 0, 0, '');
DELETE FROM `creature_text` WHERE `entry`=864601 AND `groupid`=3 AND `id`=0;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (864601, 3, 0, 'Bah! Who cares about some old, dusty relics? I came here to bash some Alliance heads in!', 12, 0, 100, 1, 0, 0, '');
DELETE FROM `creature_text` WHERE `entry`=864601 AND `groupid`=4 AND `id`=0;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES (864601, 4, 0, 'All I care about is that we get to bring the battle to the humans again. I\'ve been itchin\' for a proper fight!', 12, 0, 100, 1, 0, 0, '');
