-- --------------------------------------------------------
-- Host:                         logon.hellscream.org
-- Server version:               5.5.9-log - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL Version:             10.3.0.5771
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table worldlive.db_script_string
CREATE TABLE IF NOT EXISTS `db_script_string` (
  `entry` int(10) unsigned NOT NULL DEFAULT '0',
  `content_default` text NOT NULL,
  `content_loc1` text,
  `content_loc2` text,
  `content_loc3` text,
  `content_loc4` text,
  `content_loc5` text,
  `content_loc6` text,
  `content_loc7` text,
  `content_loc8` text,
  `content_loc9` text,
  `content_loc10` text,
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Dumping data for table worldlive.db_script_string: 278 rows
DELETE FROM `db_script_string`;
/*!40000 ALTER TABLE `db_script_string` DISABLE KEYS */;
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `content_loc9`, `content_loc10`) VALUES
	(2000000104, '... oops.', NULL, NULL, '... Uups.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000077, '%s gestures to the pitcher of water sitting on the edge of the well.', NULL, NULL, 'Ah, das ist genau richtig! Ich glaube, ich hole mir noch ein paar... könnt ihr für mich auf diese Fässer aufpassen, $N?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000102, 'Oh, darn...', NULL, NULL, 'Oh, verdammt...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000103, 'Ok, let\'s get started!', NULL, NULL, 'Na gut! Dann mal los!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000033, 'Keep moving!', NULL, NULL, 'Weitergehen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000034, 'Come, $N. Lord Stormrage awaits.', NULL, NULL, 'Kommt, $N. Fürst Sturmgrimm erwartet Euch.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000035, 'Warriors of Dragonmaw, gather \'round! One among you has attained the rank of highlord! Bow your heads in reverence! Show your respect and allegiance to Highlord $N!', NULL, NULL, 'Krieger des Drachenmals, schart euch zusammen! Einer unter euch hat den Rang des Hochlords erreicht! Verneigt euch aus Ehrfurcht! Zeigt eure Hochachtung und Loyalität gegenüber Hochlord $N!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000036, 'Lord Illidan will be here shortly.', NULL, NULL, 'Fürst Illidan wird hier bald eintreffen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000037, 'All hail Lord Illidan!', NULL, NULL, 'Es lebe Fürst Illidan!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000038, 'Lord Illidan, this is the Dragonmaw that I, and others, have told you about. He will lead us to victory!', NULL, NULL, 'Fürst Illidan, dies ist das Drachenmal über das ich, und andere, euch erzählt haben. Es wird uns zum Sieg verhelfen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000039, 'But... My lord, I do not understand. $N... He is the orc that has...', NULL, NULL, 'Aber... Mein Fürst, ich verstehe nicht. $N... Er ist der Ork, der...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000040, 'It will be done, my lord.', NULL, NULL, 'Es wird vollbracht, mein Fürst.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000041, 'So you thought to make a fool of Mor\'ghor, eh? Before you are delivered to Lord Illidan, you will feel pain that you could not know to exist. I will take pleasure in exacting my own vengeance.', NULL, NULL, 'Ihr dachtet also Ihr könntet Mor\'ghor zum Narren halten, wie? Bevor Ihr Fürst Illidan übergeben werdet, werdet Ihr Schmerzen fühlen, deren Existenz Euch bisher unbekannt war. Mit Freuden werde ich meine Rache auskosten.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000045, 'There\'s nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right!', NULL, NULL, 'Es geht doch nichts über kochend heißes Morgengebräu an einem kalten Morgen in Dun Morogh! Danach kann der Tag kommen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000046, 'Oooooo hot hot hot! If that won\'t put spring in your step, I don\'t know what will!', NULL, NULL, 'Ooooh! Heiß! Heiß! Heiß! Wenn Euch das nicht auf Touren bringt, kann ich Euch auch nicht helfen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000047, 'Ribbit! No!! This cannot...ribbit...be! You have duped me with...ribbit...your foul trickery! Ribbit!', NULL, NULL, 'Verflixt! Nein!!! Das kann... verflixt... nicht sein. Ihr habt mich mit Euren faulen Tricks betrogen. Verflixt', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000048, 'Now let us place this rare earth in my planter...', NULL, NULL, 'Nun lasst uns diese Erde in meinen Pflanztopf stecken...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000049, 'Thank you again, $N. This rare earth will be very helpful in my experiments.', NULL, NULL, 'Vielen Dank nochmal, $N. Diese Rare Erde wird mir bei meinen Experimenten sehr nützlich sein.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000055, 'How many more of you grunts do I need to send back to mommy and daddy in a body bag before you grow a brain and realize that runnin\' head first into a Legion kill squad is suicide? And don\'t nod your thick skulls at me as if you know what I\'m talkin\' about!', NULL, NULL, 'Wieviele von euch Grunzern muss ich noch zu Mammi und Daddi im Leichensack zurückschicken, bevor ihr endlich einseht, dass es Selbstmord ist mit dem Kopf voraus in eine Gruppe dieser mörderischen Legion zu laufen? Und nickt nicht mit euren dicken Schädeln als würdet ihr wissen wo von ich rede!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000056, 'Hey there, Belm! Give me a mug of Thunder Ale, and one for my good friend $N.', NULL, NULL, 'Hey, Belm! Gib mir einen Becher Donnerbier, und einen für meinen guten Freund $N.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000057, 'Spirits of Water, I give you praise, and I beg of you a favour. You have heard $N\'s pleas, and I trust his inent is noble. Please, will you aid us?', NULL, NULL, 'Geister des Wassers, ich preise euch und erflehe einen Gefallen von euch. Ihr habt die Bitten gehört, die $N an euch gerichtet hat, und ich bin mir sicher, ihre Beweggründe sind lauter und edel. Bitte, helft uns.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000058, 'Thank you great spirit. Thank you!', NULL, NULL, 'Dank Euch, großer Geist. Danke!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000060, 'By the stars! A spirit has been summoned!', NULL, NULL, 'Bei den Sternen! Ein Geist wurde beschworen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000061, 'It\'s a mystery of the past indeed! But a key to our future!', NULL, NULL, 'Es ist zwar ein Geheimnis der Vergangenheit! Aber es ist ein Schlüssel für unsere Zukunft!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000062, 'The threat be over! $N be savin\' us all!', NULL, NULL, 'Die Gefahr wird bald vorüber sein! $N wird uns alle beschützen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000063, 'Follow me, good $C. I\'ll have your barding done faster than I could down a Dwarven stout. Mmmm... stout.', NULL, NULL, 'Folgt mir, lieber $C. Ich werde euer Pferdegeschirr schneller fertig gestellt haben, als ich einen stämmigen Zwerg bezwingen kann. Mmmm... stämmig.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000064, 'Well, that should do it. Come now, back to the shop to finish our business!', NULL, NULL, 'Gut, das sollte seinen Zweck erfüllen. Kommt nun, lasst uns zurück zu dem Verkaufsstand gehen, um unser Geschäft abzuschließen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000065, 'We will suffer no demon\'s servant in our lands!', NULL, NULL, 'Wir werden keine Dämonendiener in unsere Ländern dulden!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000066, 'Peace and patience be with you, $N. Remain strong always.', NULL, NULL, 'Friede und Geduld sei mit Euch, $N. Bleibt immer stark.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000067, 'What are you doing in Ysera\'s realm, interloper? Leave us, I say! Your kind are not welcome here!', NULL, NULL, 'Was macht ihr im Reich von Ysera, Eindringling? Fort von hier, sage ich! Eure Sorte ist hier nicht willkommen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000068, 'You -- you\'re not one of them! Let\'s get out of sight before they find us! Hurry!', NULL, NULL, 'Ihr -- Ihr seid nicht einer von ihnen! Lasst und hier verschwinden bevor sie uns finden! Beeilt Euch!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000069, 'They\'re following me, $R! Quickly, tell me why you\'re here before we\'re discovered! If they catch up to me, it will mean my death and yours!', NULL, NULL, 'Sie verfolgen mich, $R! Schnell, erzählt mir warum Ihr hier seid bevor wir entdeckt werden! Wenn sie mich fangen, wird das meinen Tod bedeuten und den Euren ebenfalls!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000070, 'It would\'ve taken years to find the Book of the Raven without you, young sparrowhawk. Return to your home in Nagrand with our gratitude.', NULL, NULL, 'Es hätte ohne Euch Jahre gedauert das Buch des Raben zu finden, junger Sperber. Kehrt mit unserer Dankbarkeit in Eure Heimat nach Nagrand zurück.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000071, 'This is it! This is really it -- the Book of the Raven!', NULL, NULL, 'Das ist es! Das ist es wirklich -- Das Buch des Raben!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000072, 'It\'s all here... how the raven\'s followers captured and subdued the sprints of rivals, trapping them forever within stone statues! The tablet even mentions the raven god\'s name -- Anzu. I\'d thought it was lost to history!', NULL, NULL, 'Es ist alles hier... wie die Verfolger der Raben die Sprinter der Rivalen gefangen und unterworfen haben und sie für immer in Steinstatuen gefangen genommen haben! Die Schreibtafel erwähnt sogar den Namen des Rabengottes -- Anzu. Ich hätte gedacht dieser wäre im Laufe der Zeit verloren gegangen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000073, 'There\'s something else here, too. After a discription of a bloody battle and the downfall of the raven, there\'s a prophecy. Anzu will haunt the dreams of his enemies, twisting them to affect a return to this world...', NULL, NULL, 'Hier ist sogar noch etwas. Nach der Beschreibung eines blutigen Krieges und dem Untergang der Raben ist hier eine Prophezeiung. Anzu wird seine Feinde in deren Träumen heimsuchen und sie dazu überreden ihm die Rückkehr in diese Welt zu ermöglichen...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000074, 'The tablet has the confirmation we need, just as I thought. Now, we have to use this information to draw out and defeat this Anzu before he can do any more damage to the Emerald Dream!', NULL, NULL, 'Die Schreibtafel gibt uns die Bestätigung, die wir benötigen, genau wie ich dachte. jetzt müssen wir diese Informationen gebrauchen, um auszuziehen und Anzu zu besiegen bevor er dem smaragdgrünen Traum noch mehr Schaden zufügen kann!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000075, 'Since the sparrowhawks have proven such a success in hunting down the raven stones, Watcher Elaira has trained another one to relay my voice at a great distance. He can help us communicate as you investigate the bird spirits revealed in the tablet!', NULL, NULL, 'Seit die Sperber so einen großen Erfolg bei der Jagd nach den Rabensteine verbucht haben, hat Behüterin Elaira einen Weiteren trainiert, um meine Stimme über eine große Distanz zu übertragen. Er kann uns helfen miteinander zu kommunizieren während ihr den Vogelgeist der in der Schreibtafel gefangen ist erkundet!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005000, 'Poor Dorius. If I ever get my hands on those Dark Irons, so help me...', NULL, NULL, 'Armer Dorius. Falls ich jemals diese Dunkeleisen erwische, dann helft mir...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005001, 'Opus wants some Cuergo\'s Gold... with worm.', NULL, NULL, 'Opus will etwas Gold von Cuergo... mit Wurm.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005002, 'Bijou lost! SQUAWK! *cough', NULL, NULL, 'Bijou ist verloren! KRÄCHZ! *hust*', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005003, 'Kibler is being investigated by G.E.T.A.', NULL, NULL, 'Kibler wird derzeit von der G.E.T.A. geprüft.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005004, 'Bijou knows where treasures are hidden.', NULL, NULL, 'Bijou weiß, wo die Schätze versteckt sind.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005005, 'Dragons controlling orcs!? SQUAWK!', NULL, NULL, 'Großdrachen kontrollieren Orcs!? KRÄCHZ!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005006, 'They all go to the Spire but none never come back... just like Bijou.', NULL, NULL, 'Alle gehen zur Spitze, aber keiner kommt zurück... genau wie Bijou.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005007, 'Ask Kibler about the treasure! SQUAWK!', NULL, NULL, 'Fragt Kibler nach dem Schatz! KRÄCHZ!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005008, 'SQUAWK!! *cough* *cough* I need to quit smoking!', NULL, NULL, 'KRÄCHZ!! *hust* *hust* Ich muss mit dem Rauchen aufhören!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005009, 'Well done, soldiers! At ease!', NULL, NULL, 'Gut gemacht, Soldaten! Rührt euch!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005010, 'Zug zug! Happy to help!', NULL, NULL, 'Zug zug! Freut sich zu helfen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005011, 'Yes right away momma!', NULL, NULL, 'Ja auf der Stelle Mama!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005012, 'Mysterious hoofprints, scorched shields, stray badges... how do we make sense of all this?', NULL, NULL, 'Geheimnisvolle Hufabdrücke, versengte Schilde, seltsame Abzeichen... wie passt das nur alles zusammen?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005013, 'I don\'t think Drazzit\'s going to have any luck finding anyone to kill this raptor. I mean, he\'s already raised the reward twice...', NULL, NULL, 'Ich glaube kaum, dass Drazzit jemanden finden wird, der seine verdammten Raptoren jagt. Ich meine, er hat die Belohnung schon zweimal erhöht...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005014, 'But this the only building that fit Brogg! Goblins make buildings too small!', NULL, NULL, 'Aber dies ist das einzige Gebäude in das Brogg passt! Goblins machen die Gebäude viel zu klein!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005015, 'I thought we talked about this, Brogg. You can\'t stay in this building. Sure, it can house you, but there\'s no room for anyone else!', NULL, NULL, 'Ich dachte wir haben über dies gesprochen, Brogg. Du kannst in diesem Gebäude nicht bleiben. Näturlich, du kannst darin wohnen, aber es ist kein Platz für irgendjemand Anderen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005016, 'Yes, we said you can stay here, but this building is our headquarters! All of our manuals and blueprints are stored here!', NULL, NULL, 'Ja, wir haben gesagt, dass Ihr hier bleiben könnt, aber dieses Gebäude ist unser Hauptquartier! All unsere Unterlagen und Pläne werden hier aufbewahrt!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005017, 'I\'m inclined to say they made ogres too big! I can see I\'m not going to convince you to move now, but don\'t think this is permanent!', NULL, NULL, 'Ich widerspreche nur ungern, aber wenn Ihr mich fragt, seid ihr Oger einfach nur zu groß! Ich sehe schon, heute werde ich Euch wohl nicht zu einem Umzug bewegen können. Aber glaubt nicht, dass Ihr auf ewig hier wohnen könnt!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005018, 'Ah, this must be him now... no?', NULL, NULL, 'Ah, das muss er jetzt sein... nein?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005019, 'You might wanna stand back. Fish guttin\' is a dirty job.', NULL, NULL, 'Ihr solltet zurücktreten. Das Ausnehmen von Fischen ist eine schmutzige Arbeit.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005020, 'It\'s good to see you defending Theramore with pride, friend.', NULL, NULL, 'Es ist gut zu sehen, dass Ihr Theramore mit Stolz verteidigt, Freund.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005021, 'When you\'re off duty, let\'s go to the inn. I\'ll buy a round and we can reminisce about the good old days.', NULL, NULL, 'Lasst uns zum Gasthaus gehen, wenn Ihr Dienstschluss habt. Ich gebe eine Runde aus und wir können uns über die gute alte Zeit unterhalten.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005022, 'Wouldn\'t you like to bring those days back? I have some friends who know just the way to do that.', NULL, NULL, 'Sehnt Ihr Euch nicht auch die gute alte Zeit herbei? Ich habe da ein paar Freunde, die uns bei der Erfüllung dieses Wunsches behilflich sein können...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005023, 'Every item that I have for sale I acquired myself. You have my personal guarantee of authenticity.', NULL, NULL, 'Jeden Gegenstand, den ich verkaufe, habe ich selbst erlangt. Ihr habt meine persönliche Garantie auf Echtheit.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005024, 'It\'s getting away!', NULL, NULL, 'Es entkommt!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005025, 'Prizes! Get your prizes right here! Get over here and turn in your Darkmoon Faire Prize Tickets for valuable prizes!', NULL, NULL, 'Gewinne! Holt Eure Gewinne direkt hier ab! Kommt her und löst Eure Gewinnlose des Dunkelmond-Jahrmarkts gegen wertvolle Gewinne ein!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005026, 'Come speak with me, and what once was cloudy shall become crystal clear.', NULL, NULL, 'Kommt sprecht mit mir, und was einst verschwommen war soll kristallklar werden.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005027, 'The Lich King\'s forces are building. It is imperative that our timetable supports his plans.', NULL, NULL, 'Die Macht des Lichkönigs wird stärker. Es ist von äußerster Wichtigkeit, dass unser Zeitplan seinem Vorhaben entspricht!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005028, 'Tomorrow we will begin training of our promising dragons, so don\'t forget your chew toys.', NULL, NULL, 'Morgen werden wir mit dem Training unserer vielversprechenden Drachen beginnen, also vergesst Eure Kauspielzeuge nicht.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005029, 'Our oldest clutch of dragons are still far from maturity, but with patience and study, we are confident the dragons will soon be ready.', NULL, NULL, 'Unser ältesten Gelege von Drachen sind noch immer weit von der Reife entfernt, aber mit Geduld und Studien sind wir überzeugt, dass die Dachen bald fertig sein werden.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005030, 'If you wait to come see me, there may be nothing left!', NULL, NULL, 'Wenn Ihr wartet um mich zu sehen, dann wird vielleicht nichts übrig sein!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005031, 'I come from the land down under... where women plague and men sunder.', NULL, NULL, 'Ich komme aus dem Land weit im Süden... wo die Frauen umtreiben und die Männer sich zerreisen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005032, '...And then the tauren said, "13 INCHES!"', NULL, NULL, '...Und dann sagte der Taure, "33 ZENTIMETER!"', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005033, 'Come one, come all! Welcome to the Darkmoon Faire! Do you crave adventure? Do you seek exotic and mysterious treasures? Then look no further! You, my friend, have come to the right place! Dive right in and take part in all that the Faire has to offer! We\'ll be at this location all week, so be sure to tell your friends and loved ones!', NULL, NULL, 'Herbei, herbei! Willkommen auf dem Dunkelmond-Jahrmarkt! Ist euch nach Abenteuern zumute? Seid ihr auf der Suche nach mystischen, exotischen Schätzen? Dann sucht nicht weiter, denn wir haben alles was ihr begehrt! Taucht ein in eine Welt voller Wunder und erlebt was der Jahrmarkt zu bieten hat! Wir gastieren hier noch die ganze Woche über. Vergesst also nicht euren Freunden und Lieben Bescheid zu sagen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005034, 'Welcome one and all to the Darkmoon Faire, the greatest event in all the worlds! We have it all... delicious food, strong drinks, exotic artifacts, fortunes read, amazing prizes and excitement without end! Don\'t forget to turn in your Darkmoon Faire Prize Tickets to Gelvas Grimegate! All it takes is five or more and you\'re on your way to the most wondrous prizes in all of Outland. Everybody is a winner', NULL, NULL, 'Der einzigartige Dunkelmond-Jahrmarkt heißt euch willkommen! Hier findet ihr alles was das Herz begehrt... herzhaftes Essen, gutes Bier, exotische Artefakte und Tränke! Vielleicht sogar ein Blick in die Zukunft! Fantastische Preise und Vergnügen ohne Ende erwarten euch! Vergesst nicht eure Dunkelmond-Gewinnlose bei Gelvas Rußgatter einzulösen! Mit nur fünf Losen oder mehr seid ihr dabei und könnt zwischen den wunderbarsten Preisen in ganz Azeroth wählen. Bei uns ist jeder ein Gewinner!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005035, 'It\'s getting away!', NULL, NULL, 'Es entkommt!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005036, 'Please! I must feed on something soon... A mana crystal... a shard... anything! The pain is unbearable!', NULL, NULL, 'Bitte! Ich muss bald etwas fressen... Einen Manakristall... einen Splitter... irgendetwas! Der Schmerz ist unerträglich!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005037, 'I might just have to go hunting for that Wretched beast now that there\'s a bounty on his head.', NULL, NULL, 'Vielleicht sollte ich einfach auf die Jagd nach dieser elenden Bestie gehen, jetzt wo eine Belohnung auf ihren Kopf ausgesetzt ist.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005038, 'Tell us! Where does you leader hide?', NULL, NULL, 'Redet! Wo versteckt sich Euer Anführer?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005039, 'The wind speaks of our enemies\' movements, Ashyen. The Naga will attack again.', NULL, NULL, 'Der Wind berichtet von den Bewegungen unserer Gegner, Ashyen. Die Naga werden erneut angreifen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005040, 'Very well. When that decision is made, I will be ready. Let us hope it won\'t be too late.', NULL, NULL, 'Sehr gut. Wenn diese Entscheidung getroffen wurde, werde ich bereit sein. Lasst uns hoffen, dass es nicht zu spät sein wird.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005041, 'I will do my best to take care of the children, Grandmother.', NULL, NULL, 'Ich werde mein Bestes geben um auf die Kinder aufzupassen, Großmutter.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005042, 'New posting up! Adventurers and heroes, gather round the bulletin board!', NULL, NULL, 'Neues Plakat angebracht! Abenteurer und Helden, versammelt euch um das schwarze Brett.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005043, 'I WILL DESTROY ALL', NULL, NULL, 'ICH WERDE ALLES ZERSTÖREN', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005044, 'US ALREADY ALL ANYMORE AND ANYMORE', NULL, NULL, 'UNS ALLE, MEHR UND MEHR', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005045, 'Just don\'t ask me where I got it...', NULL, NULL, 'Fragt einfach nicht woher ich es habe...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005048, 'Having a good time?', NULL, NULL, 'Habt Ihr eine schöne Zeit?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005049, 'I have another reading from the nether.', NULL, NULL, 'Ich habe eine weitere Lesung aus dem Nether.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005050, 'Well hand it overand let\'s see what you got!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005051, 'Great Gazlowe!', NULL, NULL, 'Klasse, Gazlowe!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005052, 'Hey, you there. Want some candy?', NULL, NULL, 'Hey, Ihr da! Wollt Ihr ein paar Süßigkeiten?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005053, 'Bip!', NULL, NULL, 'Bip!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005054, 'Bip!', NULL, NULL, 'Bip!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005055, 'Bip!', NULL, NULL, 'Bip!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005056, 'Right. We just busted our tails to haul all of this stuff up here, and you want us to work more?', NULL, NULL, 'Genau. Wir haben gerade unsere Rücken ruiniert um all diesen Kram hier hoch zu schleppen, und Ihr wollt, dass wir noch mehr arbeiten?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005057, 'Crybaby! Crybaby!', NULL, NULL, 'Heulsuse! Heulsuse!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005058, 'Baby wants her dolly!', NULL, NULL, 'Das Baby will seine Puppe!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005059, 'I wonder if your dolly can swim!', NULL, NULL, 'Ich frage mich, ob deine Puppe schwimmen kann!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005060, 'Ha ha! I have Betsy!', NULL, NULL, 'Haha! Ich habe Betsy!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005061, 'Baby wants her dolly!', NULL, NULL, 'Ich habe deine Puppe! Nana, nana!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005062, 'I have your dolly! Nyah nyah!', NULL, NULL, 'Gib mir meine Puppe!!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005063, 'Crybaby! Crybaby!', NULL, NULL, 'Tu Betsy nicht weh, du Widerling!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005064, 'Baby wants her dolly!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005065, 'I wonder if your dolly can swim!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005066, 'Ha ha! I have Betsy!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005067, 'Baby wants her dolly!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005068, 'I have your dolly! Nyah nyah!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005069, 'Crybaby! Crybaby!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005070, 'Baby wants her dolly!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005071, 'I wonder if your dolly can swim!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005072, 'Ha ha! I have Betsy!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005073, 'Baby wants her dolly!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005074, 'I have your dolly! Nyah nyah!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005075, 'Crybaby! Crybaby!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005076, 'Baby wants her dolly!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005077, 'I wonder if your dolly can swim!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005078, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005079, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005080, 'Don\'t hurt Betsy, you meanie!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005081, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005082, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005083, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005084, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005085, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005086, 'Don\'t hurt Betsy, you meanie!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005087, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005088, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005089, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005090, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005091, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005092, 'Don\'t hurt Betsy, you meanie!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005093, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005094, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005095, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005096, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005097, 'Gimmie my dolly!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005098, 'Don\'t hurt Betsy, you meanie!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005099, 'Fresh bread for sale', NULL, NULL, 'Frisches Brot zu verkaufen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005100, 'Get it while its hot', NULL, NULL, 'Greif zu, solange es noch heiß ist!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005101, 'Fresh bread for sale', NULL, NULL, 'Frisches Brot zu verkaufen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005102, 'Get it while its hot', NULL, NULL, 'Greif zu, solange es noch heiß ist!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005103, 'Jack and Jill my wrinkled patoot! I do all the water luggin round here.', NULL, NULL, 'Ich rackere mir hier die alten Knochen ab! Schleppe sämtliches Wasser aus der Gegend heran.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005104, 'Wheres the water Emma? Get the water Emma? Ifn it werent fer me that lot wouldnt know what water looks like.', NULL, NULL, 'Wo ist das Wasser, Emma? Hast du Wasser geholt, Emma? Wenn ich nicht wäre, würd\' das Pack gar nicht wissen, wie Wasser aussieht.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005105, 'Of Course Im talking to myself. Only way to get a decent conversation in this city.', NULL, NULL, 'Natürlich rede ich mit mir selbst. Das ist die einzige Möglichkeit, in dieser Stadt ein nettes Gespräch zu führen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005106, 'As if I dont have better things to do in my old age than carry buckets of water.', NULL, NULL, 'Als ob ich auf meine alten Tage nichts Besseres zu tun hätte, als Wassereimer zu schleppen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005107, 'Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.', NULL, NULL, 'Mir scheint\'s, als ginge ich hundert Mal am Tag den ganzen Weg zum Brunnen, um immer noch mehr Wasser zu holen. Keinen Respekt vor den Alten, ich sag\'s Euch.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005108, 'Deja vu. For a moment I thought I was back home... before the plague...', NULL, NULL, 'Déjà-vu. Für einen Moment dachte ich, ich wäre zu Hause... vor der Seuche...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005109, 'They say he can turn into a raven sometimes.', NULL, NULL, 'Sie sagen er kann sich manchmal in einen Raben verwandeln.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005110, 'They say he can turn into a raven sometimes.', NULL, NULL, 'Sie sagen er kann sich manchmal in einen Raben verwandeln.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005111, 'And then the rabbit just bit his head off... I swear.', NULL, NULL, 'Und dann hat der Hase einfach seinen Kopf abgebissen... Ich schwöre es.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005112, 'I swear, people have actualy seen them. Pandaren really do exist!!', NULL, NULL, 'Ich schwöre Euch, manche haben sie bereits gesehen. Pandaria existieren wirklich!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005113, 'You know why Orcs eyes glow red? It\'s because they drink blood!', NULL, NULL, 'Wisst Ihr warum die Augen von Orcs rot glühen? Dies ist so, weil sie Blut trinken!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005114, 'I dont think there\'s any fish in these canals.', NULL, NULL, 'Ich glaube nicht, dass es irgendwelche Fische in diesen Kanälen gibt.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005115, 'And that\'s how Lother killed thirty six orcs with his bare hands!', NULL, NULL, 'Und dies ist die Geschichte, wie Lother sechsunddreißig Orcs mit seinen bloßen Händen tötete!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005116, 'Eww... that\'s not a fish!', NULL, NULL, 'Ähh... das ist kein Fisch!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005117, 'I got worm guts on my shoes.', NULL, NULL, 'Ich habe Eingeweide von Würmern auf meinen Schuhen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005118, 'I think i see something.', NULL, NULL, 'Ich glaube ich sehe etwas.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005119, 'Eww... that\'s not a fish!', NULL, NULL, 'Ähh... das ist kein Fisch!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005120, 'I think i see something.', NULL, NULL, 'Ich glaube ich sehe etwas.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005121, 'I hope that was a fish!', NULL, NULL, 'Ich hoffe das war ein Fisch!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005122, 'Worm goes on the hook, hook goes in the water, Fish is in the water, our fish.', NULL, NULL, 'Wurm geht auf den Haken, der Haken geht in\'s Wasser, Fische sind im Wasser, unsere Fische.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005123, 'Can you imagine?', NULL, NULL, 'Könnt Ihr Euch das vorstellen?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005124, 'Really?', NULL, NULL, 'Wirklich?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005125, 'Wow.', NULL, NULL, 'Wow!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005126, 'My father says that\'s just a story.', NULL, NULL, 'Mein Vater sagt es ist bloß eine Geschichte.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005127, 'Really?', NULL, NULL, 'Wirklich?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005128, 'Wow.', NULL, NULL, 'Wow!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005129, 'That\'s neat.', NULL, NULL, 'Das ist hübsch.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005130, 'Wow.', NULL, NULL, 'Wow!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005131, 'Really?', NULL, NULL, 'Wirklich?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005132, 'Look alive, dogs! We got an operation to run here!', NULL, NULL, 'Wacht auf, Hunde! Wir haben hier eine Aufgabe zu bewältigen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005133, 'Having a good time?', NULL, NULL, 'Habt Ihr eine schöne Zeit?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005134, 'Here we have the Cathedral of Light, the center of spiritual enlightenment here in Stormwind.', NULL, NULL, 'Hier ist die Kathedrale des Lichts, das Zentrum der geistigen Erleuchtung hier in Sturmwind.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005135, 'Yes, that is true. Paladins and Priests alike train their skills and research great truths behind the walls of the Cathedral.', NULL, NULL, 'Ja, das ist wahr. Paladine und Priester zugleich trainieren ihre Fähigkeiten und erforschen großartige Wahrheiten hinter den Mauern der Kathedrale.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005136, 'Children if you would please follow me, we will now be going to see the keep where King Anduin Wrynn himself sits on this throne.', NULL, NULL, 'Kinder, wenn Ihr mir bitte folgen würdet, wir werden nun die Festung ansehen, in der König Anduin Wrynn persönlich auf seinem Thron sitzt.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005137, 'Here we have Stormwind Keep. Built upon the ruins of Stormwind Castle, which was destroyed by the Horde in the first Great War.', NULL, NULL, 'Hier haben wir die Festung von Sturmwind. Gebaut auf den Ruinen der Burg von Sturmwind, welche von der Horde im ersten großen Krieg zerstört wurde.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005138, 'When the Horde was shattered, men returned here and began to rebuild the once great city as a testament to our own survival.', NULL, NULL, 'Als die Horde zerschmettert wurde, kehrten Männer hierher zurück und begannen mit dem Aufbau der einst großen Stadt als Testament unseres eigenen Überlebens.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005139, 'Yes, well...let\'s head on to the monument dedicated to the heroes of the two Great Wars, the Valley of Heroes. Follow Me.', NULL, NULL, 'Nun gut... lasst uns nun zu dem Monument gehen, welches den Helden der zwei großen Kriege gewidmet ist, dem Tal der Helden. Folgt mir.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005140, 'Isn\'t it amazing, children? All who enter the city must walk beneath the watchful eyes of the greatest heroes of our lands.', NULL, NULL, 'Ist das nicht beeindruckend, Kinder? Jeder der die Stadt betritt muss unter den wachsamen Augen der größten Helden unserer Länder laufen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005141, 'Breathtaking. Children, when we return to the school, you will each give an oral report on one of these legendary people.', NULL, NULL, 'Atemberaubend. Kinder, wenn wir zur Schule zurückkehren, wird jeder von Euch einen mündlichen Vortrag über eine dieser legendären Personen halten.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005142, 'Now, take another long look before we make our way to the Holy District and the great Cathedral of Light.', NULL, NULL, 'Nun, schaut noch einmal zurück bevor wir unseren Weg in das heilige Distrikt und die großartige Kathedrale des Lichts fortsetzen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005143, 'This will never do..', NULL, NULL, 'Das funktioniert niemals...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005144, 'This must be fixed!', NULL, NULL, 'Das muss repariert werden!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005145, 'How can anyone live like this!?', NULL, NULL, 'Wie kann irgendjemand so leben!?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005146, 'Duck!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005147, 'Don\'t go close to the lake! It\'s haunted!', NULL, NULL, 'Geht nicht zu nah an den See! Er ist verflucht!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005148, 'Putting in twelve centers of focus might allow the magical energies to form more solidly, adding the necessary stability.', NULL, NULL, 'Zwölf Fokuszentren einzubringen könnte es den magischen Energien erlauben, sich stabiler zu formen, da sie die notwendige Stabilität einbringen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005149, 'At least we would not be around to have to clean it up.', NULL, NULL, 'Wenigstens wären wir nicht hier, um es saubermachen zu müssen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005150, 'Only if we did not follow the proper initialization procedures.', NULL, NULL, 'Nur, wenn wir nicht die richtigen Initialisierungsprozeduren befolgen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005151, 'The resultant energies could collapse though, and that could cause an energy flux that would give you a migraine for weeks.', NULL, NULL, 'Die resultierenden Energien könnten natürlich kollabieren und das könnte wiederum einen Energiefluss erzeugen, der Euch die nächsten Wochen eine Migräne bescheren würde.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005152, 'Only if we did not follow the proper initialization procedures.', NULL, NULL, 'Nur, wenn wir nicht die richtigen Initialisierungsprozeduren befolgen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005153, 'Only if we did not follow the proper initialization procedures.', NULL, NULL, 'Nur, wenn wir nicht die richtigen Initialisierungsprozeduren befolgen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005154, 'At least we would not be around to have to clean it up.', NULL, NULL, 'Wenigstens wären wir nicht hier, um es saubermachen zu müssen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005155, 'But isn\'t that what caused the initial problems with Adept Syleria\'s magical formula?', NULL, NULL, 'Aber ist es nicht genau das, was die anfänglichen Probleme mit Adept Sylerias magischen Formeln verursachte?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005156, 'I suppose that could work, if we had twenty people to cast it with.', NULL, NULL, 'Ich denke, dass es funktionieren könnte, wenn wir zum Zaubern zwanzig Leute zur Verfügung hätten.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005157, 'But what if the resulting frequency shift were to send magical feedback up the flows?', NULL, NULL, 'Aber was passiert, wenn die resultierende Frequenzverschiebung eine magische Rückkopplung durch die Ströme schickt?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005158, 'When the positively aligned energies collide with the negatively charged energies, they don`t negate one another.', NULL, NULL, 'Wenn die positiv ausgerichteten Energien mit den negativ aufgeladenen Energien kollidieren, heben sie einander nicht auf.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005159, 'That will unbalance the magical focus, though, and cause a reverse vibration in the ether.', NULL, NULL, 'Das wird jedoch den magischen Fokus aus der Balance bringen und im Äther eine umgekehrte Vibration verursachen', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005160, 'But wouldn`t that mean crossing the streams? Isn`t that really bad?', NULL, NULL, 'Würde das nicht ein Kreuzen der Strahlen bedeuten? Ist das nicht ziemlich schlimm?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005161, 'Why can\'t we just shift the array to compensate for the variance in the flux?', NULL, NULL, 'Warum können wir nicht einfach den Bereich ändern, um die Abweichung der Durchflussmenge auszugleichen?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005162, 'But isn\'t that what caused the initial problems with Adept Syleria\'s magical formula?', NULL, NULL, 'Aber ist es nicht genau das, was die anfänglichen Probleme mit Adept Sylerias magischen Formeln verursachte?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005163, 'I think not, I don\'t need to be blown up again.', NULL, NULL, 'Ich denke nicht. Ich möchte nicht wieder hochgejagt werden.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005164, 'Maginor says that twisting alternating flows of positive energy actually creates a much more stable flow.', NULL, NULL, 'Maginor sagt, dass Wechselströme positiver Energie in der Tat einen viel stabileren Fluss erzeugen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005165, 'But wouldn`t that mean crossing the streams? Isn`t that really bad?', NULL, NULL, 'Aber würde das nicht bedeuten die Ströme zu überqueren? Ist das nicht total schlecht?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005166, 'But isn\'t that what caused the initial problems with Adept Syleria\'s magical formula?', NULL, NULL, 'Aber ist es nicht genau das, was die anfänglichen Probleme mit Adept Sylerias magischen Formeln verursachte?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005167, 'Is it true that the paladins train here?', NULL, NULL, 'Ist es wahr, dass die Paladine hier trainieren?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005168, 'Why do we have to learn this stuff anyway?', NULL, NULL, 'Warum müssen wir überhaupt dieses Zeug lernen?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005169, 'If we reverse the Essence flows perhaps we can alter the polarity.', NULL, NULL, 'Wenn wir die Essenzströme umkehren, können wir vielleicht auch die Polarität ändern.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005170, 'What if we used three focuses in Tyrean pattern? That should solve it.', NULL, NULL, 'Was wäre denn, wenn wir drei Fokusse nach tyreanischem Muster einsetzen? Das sollte die Lösung sein.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005171, 'Wow, all this for a love potion. Hope he is worth it.', NULL, NULL, 'Hui, und das alles für einen liebestrank. Hoffentlich ist er es wert.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005172, 'If we use the appropriate sequence we should be ok. Will just take some serious studying before we start.', NULL, NULL, 'Wenn wir eine geeignete Sequenz benutzen, sollte es funktionieren. Es werden vor Beginn nur sorgfältige Studien nötig sein.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005173, 'The Portal will shift slightly. At this point if you cast a binding cantrip you will solidify it in place.', NULL, NULL, 'Das Portal würde sich leicht verlagern. Wenn Ihr zu diesem Zeitpunkt einen Bindezauberspruch sprecht, könnt Ihr es an Ort und Stelle verfestigen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005174, 'Wow, all this for a love potion. Hope he is worth it.', NULL, NULL, 'Hui, und das alles für einen liebestrank. Hoffentlich ist er es wert.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005175, 'But if we stabilize it with an anchor thread at the appropriate energy crux then it should work.', NULL, NULL, 'Aber wenn wir es mit einem Ankergewinde auf angemessenem Energiefluss stabilisieren könnten, sollte es funktionieren.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005176, 'What if we used three focuses in Tyrean pattern? That should solve it.', NULL, NULL, 'Was wäre denn, wenn wir drei Fokusse nach tyreanischem Muster einsetzen? Das sollte die Lösung sein.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005177, 'If we use the appropriate sequence we should be ok. Will just take some serious studying before we start.', NULL, NULL, 'Wenn wir eine geeignete Sequenz benutzen, sollte es funktionieren. Es werden vor Beginn nur sorgfältige Studien nötig sein.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005178, 'But if we stabilize it with an anchor thread at the appropriate energy crux then it should work.', NULL, NULL, 'Aber wenn wir es mit einem Ankergewinde auf angemessenem Energiefluss stabilisieren könnten, sollte es funktionieren.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005179, 'Wow, all this for a love potion. Hope he is worth it.', NULL, NULL, 'Hui, und das alles für einen liebestrank. Hoffentlich ist er es wert.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005180, 'Hello, Charys. I have my list, could you get me all of that, especially the last ingredient.', NULL, NULL, 'Hallo, Charys. Meine Liste ist fertig. Könnt Ihr mir bitte all dies besorgen, besonders die letzte Zutat?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005181, 'Sure Paige. Just be gentle.', NULL, NULL, 'Sicher Paige. Sei einfach vornehm.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005182, 'Thanks, Charys. C\'mon Paige, sweetie.', NULL, NULL, 'Danke, Charys. Komm schon Paige, Liebling.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005183, 'Mommy? Can I pet Fizzles?', NULL, NULL, 'Mammi? Kann ich Frizzles streicheln?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005184, 'Fizzles used to be a great wizard. But got turned into a rabbit when one of his spells went bad.', NULL, NULL, 'Frizzles war ein großartiger Zauberer. Aber er wurde in einen Hasen verwandelt als einer seiner Zauber schiefging.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005200, 'Charge!', NULL, NULL, 'Zaubere!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005201, 'Charge!', NULL, NULL, 'Zaubere!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005202, 'Ahh, my precious Ameenah! How wonderful to see you again.', NULL, NULL, 'Ahh, meine kostbare Ameenah! Wie schön dich wieder zu sehen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005203, 'Yer wearin down, princess, I can sense it!', NULL, NULL, 'Yer ist tot, Prinzessin, ich kann es fühlen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005204, 'Hmm, don\'t mind if I do!', NULL, NULL, 'Hmm, macht Euch keine Sorgen, denn ich mache es!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005205, 'It\'s coming along, Wafflefry. Haven\'t you got a product demonstration to do or something?', NULL, NULL, 'Es wird langsam, Waffelfritte, es wird... Hast du etwa keine Produktpräsentation zu machen, oder was?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005206, 'Be the first on your block to own the incredible Electrostatic Maculation Blaster!', NULL, NULL, 'Seid der erste aus Eurem Umfeld der den unglaublichen elektrostatischen Makulaturblaster besitzt!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005207, 'Derived from cutting edge Shattered Hand Offensive military technology, it blasts away stubborn stains with ease!', NULL, NULL, 'Abgeleitet von innovativer Militärtechnologie der Offensive der Zerschmetterten Hand, es entfernt hartnäckige Flecken mit Leichtigkeit!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005208, 'Wine stains, grass stains, even pet stains are no match for the Electrostatic Maculation Blaster!', NULL, NULL, 'Ob Rotwein-, Grasflecken oder sogar tierische Hinterlassenschaften... Kein Fleck ist dem elektrostatischen Makulationsblaster gewachsen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005209, 'Don\'t wait! Order now and receive my Ultra-Kinetic Waffle Iron at no additional charge!', NULL, NULL, 'Zögert nicht! Bestellt jetzt und Ihr erhaltet mein ultrakinetisches Waffelbügeleisen ohne Aufpreis!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005210, 'I\'ll never stop. Never...', NULL, NULL, 'Ich werde niemals aufhören. Niemals...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000078, 'How goes the barrel watching...?', NULL, NULL, 'Und wie läuft das Fassbewachen...?', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000079, 'Well, back to business for me. But it sure was nice taking that short break, and it\'s always nice drinking Thunder Ale!', NULL, NULL, 'Nun ja, ich muss mich wieder um die Arbeit kümmern. Aber so eine kleine Pause tut schon gut und so ein Donnerbier schmeckt immer!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005237, 'These fires have been burning steadily for years. Unusual dedication for trolls.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005238, 'Strange... These mosaics don\'t resemble any known troll traditions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005239, 'Yes, yes, I\'m quite certain this represents the melding of entities. Fascinating.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005240, 'One can learn volumes about a culture by studying its refuse.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005241, 'Ugh. Matted clumps of hair, molted feathers, bits of bone, partially burned material - clothing perhaps?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000082, 'I. . .I. . .don\'t. . .feel. . .right. . .', NULL, NULL, 'M... m... mir... geht... es... nicht... gut...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000083, 'My mind. . .my flesh. . .I\'m. . .rotting. . . .!', NULL, NULL, 'Mein Verstand... mein Fleisch... ich... verwese...!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000084, 'I raise my brew and hope to be rid of the likes of you! Cheers, you no good scoundrel, $N!', NULL, NULL, 'Ich erhebe mein Glas und hoffe, dass wir Euresgleichen bald los sind! Prost, Ihr nichtsnutziger Halunke, $N!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000090, 'Onu studies the parchment from the Twilight Tome...', NULL, NULL, 'Onu betrachtet das Pergament aus dem Folianten der Schattenhammerkultisten...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000091, 'Onu is struck by unleashed magic!', NULL, NULL, 'Onu wird von freigesetzter Magie getroffen', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000092, 'Hmm...', NULL, NULL, 'Hmmm...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000086, 'Denalan removes the seeds from the Glowing Fruit...', NULL, NULL, 'Denalan entfernt die Samen aus der glühenden Frucht..', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000087, 'Let\'s see how these seeds grow in my prepared soil...', NULL, NULL, 'Dann wollen wir doch mal sehen, wie diese Samen in meiner vorbereiteten Erde wachsen...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000088, 'Denalan plants fruit seeds.', NULL, NULL, 'Denalan pflanzt die Fruchtsamen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000089, 'Bogling rises from the soil!', NULL, NULL, 'Sumpfling bricht aus der Erde hervor!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000004, 'Everyone enjoying themselves so far?  That\'s great!  Welcome to the Darkmoon Faire, the greatest show on all of Azeroth!  Make sure that you speak with Yebb and his friends here while you\'re taking in Neblegear\'s Darkmoon Zoo Bizarre.', NULL, NULL, 'Ich sollte jetzt sofort beginnen, $N.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000105, 'The spirits of Stonetalon still rage, $N.', NULL, NULL, 'Die Geister des Steinkrallengebirges wüten noch immer, $N.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000106, 'I fear we may never soothe them...', NULL, NULL, 'Ich fürchte, wir werden sie niemals beschwichtigen können...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000028, 'The People of Westfall salute $N, a brave and valiant defender of freedom.', NULL, NULL, 'Das Volk von Westfall salutiert vor $N, einem mutigen und tapferen Verteidiger der Freiheit.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000095, 'Zarlman Two-Moons begins chanting as he mixes the well stones and ambercom before the Tribal Fire.', NULL, NULL, 'Zarlman Zwillingsmond beginnt zu singen, wärend er die Quellsteine und das Bernsteinkorn vor dem Stammesfeuer vermischt.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000096, 'The Water of the Seers is ready for your consumption, $N.', NULL, NULL, 'Das Wasser der Seher steht für Euch zum Trinken bereit, $N.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000097, 'Tonga Runetotem inspects the snapjaw shells...', NULL, NULL, '%s untersucht die Schnappkieferschalen...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000098, 'Hm...', NULL, NULL, 'Hm...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000099, 'Strange. Very strange...', NULL, NULL, 'Seltsam. Sehr seltsam...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000100, '$N. These shells tell me much, but I fear many more questions are now raised...', NULL, NULL, '$N. Diese Schalen sagen viel aus, aber ich fürchte, es stellen sich nun noch viel mehr Fragen...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000101, 'Ok, let\'s take a look at this thing...', NULL, NULL, 'Na gut, sehen wir uns das Ding da mal an...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005400, 'We really should fix this fence soon.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005401, '*sigh* It\'s about time to check on the cemetary again-- Ill be back in a few minutes.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005402, 'How long can it take to pick a handful of weeds?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005403, 'At this rate I could have gathered them myself!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005404, 'Ah, this must be him now... no? Bah!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005405, 'As if I had all eternity.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005406, 'We\'re running low on iron, lads! I don\'t want to see a single bar go to waste, ye hear me now?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005407, 'Not bad. Try that trick I told you about when you temper the steel.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000138, 'I hereby destroy these instruments of evil! For the Horde!', NULL, NULL, 'Hiermit zerstöre ich diese Instrumente des Bösen! Für die Horde!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005408, 'Stonemasons. . .errr. . Defias be warned:  The rusty anchor sinks tonight.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005409, '%s calls upon the mighty armies of the Scourge!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000005410, 'Armies of the Scourge, hear my call! The scarlet apocalypse has begun! Tear this land asunder and leave only death in your wake!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000005, 'We\'re back and better than ever!  It\'s the Darkmoon Faire friend, and it\'s your lucky day! Sparing no expense, we\'ve gathered wonders and treats from around the world for your delight.  Whether you\'re young or old, rich or poor, the Darkmoon Faire has it all!  Be sure to turn in your Darkmoon Faire Prize Tickets to Gelvas Grimegate, and choose from several exotic and wondrous prizes!', NULL, NULL, 'So... wo sind Nadel und Faden? Ah! Da sind sie ja...', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000006, 'Come one, come all.  Welcome to the Darkmoon Faire!  Don\'t be shy.  Step right up to Lhara and buy yourself an exotic artifact from far off lands.  If you\'re one of the lucky few who have found Darkmoon Cards, have a word with Professor Paleo.  Hungry?  Thirsty?  You\'re in luck!  Refreshments are available right here from Sylannia and Stamp.  I recommend the Darkmoon Special Reserve to wash down some Red Hot Wings.  And if the future is what you seek, then run, don\'t walk, to speak with Sayge.', NULL, NULL, 'Terenthis beginnt, einen Zauber zu wirken, als Ihr ihm den Umhang abnehmt.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000007, 'Welcome one and all to the Darkmoon Faire, the greatest event in all the world!  We have it all... delicious food, strong drink, exotic artifacts, fortunes read, amazing prizes and excitement without end!  Don\'t forget to turn in your Darkmoon Faire Prize Tickets to Gelvas Grimegate!  All it takes is five or more and you\'re on your way to the most wondrous prizes on all of Azeroth.  Everybody is a winner!', NULL, NULL, 'Geht jetzt, $N. Findet Volcor... und denkt daran, dass die Magie, die Euch beschützt, versagen wird, wenn Ihr mit anderen mehr tut als bloß zu reden.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000107, 'These aren\'t Shango\'s tracks.', NULL, NULL, 'He, $N! Vergesst nicht, eine Kiste, ein Handbuch und einen Leitstecken mitzunehmen!', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000000108, 'These tracks must belong to Shango.', NULL, NULL, '%s hört sich die Bitte von $N an.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2000006000, 'On your first try! Now, take the flame to the top of the temple and burn the scroll that you find there.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
/*!40000 ALTER TABLE `db_script_string` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
